---
# Configure logservers
- name: Configure logservers
  hosts: logservers
  become: true
  tasks:
  - name: Copy elasticsearch .dep package to client
    ansible.builtin.copy:
      src: ./debs/elasticsearch-8.12.2-amd64.deb
      dest: /tmp/elasticsearch-8.12.2-amd64.deb

  - name: Install the elasticsearch .deb package
    ansible.builtin.apt:
      deb: /tmp/elasticsearch-8.12.2-amd64.deb

  - name: Copy elasticsearch config file to client
    ansible.builtin.copy:
      src: elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml

  - name: Install the python3-pexpect
    ansible.builtin.apt:
      name: python3-pexpect
      update_cache: yes

  - name: Make sure a service unit elasticsearch.service is running
    ansible.builtin.systemd_service:
      name: elasticsearch.service 
      state: restarted
      enabled: yes 

  - name: Change password for elastic user
    ansible.builtin.expect:
      command: sudo /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -ib
      responses:
        (?i)password: "Otus1234!"
    no_log: true 
    tags:
      - elasticpass	     

  - name: Copy kibana .dep package to client
    ansible.builtin.copy:
      src: ./debs/kibana-8.12.2-amd64.deb
      dest: /tmp/kibana-8.12.2-amd64.deb

  - name: Install the kibana .deb package
    ansible.builtin.apt:
      deb: /tmp/kibana-8.12.2-amd64.deb

  - name: Copy kibana config file to client
    ansible.builtin.copy:
      src: kibana.yml
      dest: /etc/kibana/kibana.yml
      
  - name: Change password for kibana_system user
    ansible.builtin.expect:
      command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -ib
      responses:
        (?i)password: "Otus1234!"
    no_log: true 
    tags:
      - kibanapass

  - name: Make sure a service unit kibana.service is running
    ansible.builtin.systemd_service:
      name: kibana.service 
      state: restarted
      enabled: yes 

  - name: Copy logstash .dep package to client
    ansible.builtin.copy:
      src: ./debs/logstash-8.12.2-amd64.deb
      dest: /tmp/logstash-8.12.2-amd64.deb

  - name: Install the logstash .deb package
    ansible.builtin.apt:
      deb: /tmp/logstash-8.12.2-amd64.deb

  - name: Copy input config file to client
    ansible.builtin.copy:
      src: input.conf
      dest: /etc/logstash/conf.d/input.conf
      
  - name: Copy output config file to client
    ansible.builtin.copy:
      src: output.conf
      dest: /etc/logstash/conf.d/output.conf     

  - name: Copy filter config file to client
    ansible.builtin.copy:
      src: filter.conf
      dest: /etc/logstash/conf.d/filter.conf 

  - name: Make sure a service unit logstash.service is running
    ansible.builtin.systemd_service:
      name: logstash.service 
      state: restarted
      enabled: yes
          
          
          
