---
# Configure logservers
- name: Configure logservers
  hosts: logservers
  become: true
  tasks:
  - name: Install the GPG (gnupg2)
    ansible.builtin.apt:
      name: gnupg2
      update_cache: yes  
  
  - name: Import the Elasticsearch GPG-KEY
    ansible.builtin.shell: sudo rm /usr/share/keyrings/elasticsearch-keyring.gpg 2> /dev/null; wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      
  - name: Install the apt-transport-https package
    ansible.builtin.apt:
      name: apt-transport-https
      update_cache: yes

  - name: Save the repository definition to /etc/apt/sources.list.d/elastic-8.x.list
    ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
      
  - name: Install the Elasticsearch
    ansible.builtin.apt:
      name: elasticsearch
      update_cache: yes

  - name: Install the Kibana
    ansible.builtin.apt:
      name: kibana
      update_cache: yes      
